name: pdf_contract_masking_cuda
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pytorch=2.2
  - cudatoolkit=11.8
  - pip:
    - -e .
    - transformers>=4.30.0
    - tqdm
    - PyMuPDF
    - regex
    - sentencepiece
    - tokenizers
