name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install -e . || true
      - name: Download Noto Sans
        run: |
          python scripts/get_noto.py
      - name: Run tests
        run: |
          pytest -q
        env:
          PYTHONIOENCODING: utf-8name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Miniconda (with mamba)
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: latest
          auto-update-conda: true
          python-version: 3.11
          activate-environment: false
          use-mamba: true

      - name: Create conda environment from environment.yml (mamba)
        run: |
          mamba env create -f environment.yml -p ./.conda_env

      - name: Activate and run tests
        run: |
          conda run -p ./.conda_env python -m pip install --upgrade pip
          conda run -p ./.conda_env python -m pip install --upgrade setuptools wheel
          conda run -p ./.conda_env python -m unittest discover -v
